### ISSUE TITLE
Got error when install kinetic chef-solo

### ISSUE THREAD

**Issue by liwenzhu** [swiftstack/kinetic-swift#30]
Hi, 
thanks for making the awesome project, but when I first install it, after vagrant up, I got an error, here is the error stack:

```bash
================================================================================
Error executing action `run` on resource 'execute[python-kinetic-swift-install]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of python setup.py develop ----
STDOUT:
STDERR: Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'
---- End output of python setup.py develop ----
Ran python setup.py develop returned 1

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/kinetic/recipes/default.rb

104:
105: execute "python-kinetic-swift-install" do
106:   cwd "/vagrant/"
107:   command "python setup.py develop"
108:   creates "/usr/local/lib/python2.7/dist-packages/kinetic-swift.egg-link"
109: end
110:

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/kinetic/recipes/default.rb:105:in `from_file'

execute("python-kinetic-swift-install") do
  retry_delay 2
  returns 0
  command "python setup.py develop"
  retries 0
  recipe_name "default"
  cwd "/vagrant/"
  creates "/usr/local/lib/python2.7/dist-packages/kinetic-swift.egg-link"
  action "run"
  cookbook_name :kinetic
  backup 5
end

[2015-04-01T02:09:01+00:00] ERROR: Running exception handlers
[2015-04-01T02:09:01+00:00] ERROR: Exception handlers complete
[2015-04-01T02:09:01+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-04-01T02:09:01+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[python-kinetic-swift-install] (kinetic::default line 105) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of python setup.py develop ----
STDOUT:
STDERR: Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'
---- End output of python setup.py develop ----
Ran python setup.py develop returned 1
```

anyone got the same error? how can I fix it? 
thanks.

**Comment by wangyanbn** [comment]
I didn't use vagrant. It seems complex.
I just manually do the similar jobs according to the "cookbooks\swift\recipes" and  "cookbooks\kinetic\recipes" in a CentOS vm.

**Comment by charz** [comment]
@liwenzhu I committed a patch for it. Could you verify it again?

**Comment by liwenzhu** [comment]
@charz 
I tried version 1e1a7db6155feeeaa8def35ad21f5af33309f1c3 again,
and it's working! thanks
